### ISSUE TITLE
Duplicate entries in pretrain dataset

### ISSUE THREAD

**Issue by FelixSteinbauer** [Xinxinatg/RBP-TSTL#1]
I just noticed that there are a few duplicate entries in the [pre-training datasets](https://github.com/Xinxinatg/RBP-TSTL#dataset) you uploaded:

![grafik](https://user-images.githubusercontent.com/43598998/177203640-7f4f0528-6da2-4632-8f4c-47d446d9370e.png)

These 10 entries wont make a significant difference but I thought I inform you anyway.

**Comment by Xinxinatg** [comment]
Thanks @FelixSteinbauer! Will update this in the readme
